version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

    ports:
      - 8080:80
    depends_on:
      php:
        condition: service_started
  
  php:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: pingcrm
      DB_USERNAME: pingcrm
      DB_PASSWORD: pingcrm


  mariadb:
    image: mariadb:10
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306 "]
      interval: 1s
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_USER: pingcrm
      MYSQL_PASSWORD: pingcrm
      MYSQL_DATABASE: pingcrm